spring:
  application:
    name: catch-waiting-batch

  config:
    import:
      - application-data.yml
      - application-client-pos.yml
      - application-client-kafka.yml

  batch:
    job:
      name: ${job.name:NONE}

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 30
        # bulk insert 정렬 옵션
        order_inserts: true
        order_updates: true
        # bulk insert 한번에 나가는 개수
        jdbc:
          batch_size: 100

---
spring:
  config:
    activate:
      on-profile: "alpha"


---
spring:
  config:
    activate:
      on-profile: "real"

  datasource:
    username: waiting_jenkins
    password: 3waIt#14!#$!Ab


---
spring:
  config:
    activate:
      on-profile: "test"

  batch:
    jdbc:
      initialize-schema: never
