name: Pull Request catch-waiting CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
env:
  AWS_REGION: ap-northeast-2
  GH_ACTOR: ${{ secrets.GH_ACTOR }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  ci:
    name: CI
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          check-latest: true

      - name: Prepare variables for deployment
        id: prepare_vars
        run: |
          echo "Preparing variables for dev(alpha) deployment..."
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID_FOR_DEV }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY_FOR_DEV }}"
          export AWS_ACCOUNT_ID=853730445264
          export ASSUME_ROLE_SESSION=github-actions-role-session-waiting-apps
          OUTPUT_JSON=`aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID:role/github-actions-role" --role-session-name "$ASSUME_ROLE_SESSION"`
          export AWS_ACCESS_KEY_ID=`echo $OUTPUT_JSON | jq -r '.Credentials.AccessKeyId'`
          export AWS_SECRET_ACCESS_KEY=`echo $OUTPUT_JSON | jq -r '.Credentials.SecretAccessKey'`
          export AWS_SESSION_TOKEN=`echo $OUTPUT_JSON | jq -r '.Credentials.SessionToken'`
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> $GITHUB_OUTPUT
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_OUTPUT
          echo "aws_session_token=$AWS_SESSION_TOKEN" >> $GITHUB_OUTPUT
          echo "Preparing variables finished successfully!"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Test with Gradle
        run: ./gradlew clean test
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.prepare_vars.outputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.prepare_vars.outputs.aws_secret_access_key }}
          AWS_SESSION_TOKEN: ${{ steps.prepare_vars.outputs.aws_session_token }}
          APICURIO_SCHEMA_REGISTRY_URL: https://apicurio.dev.wadcorp.in/
